# Generated by Django 4.1.5 on 2023-02-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
